Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"

  config.vm.synced_folder "./data", "/vagrant_data"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     #do not sync time between guest & host
     vb.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 1]
  end
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end  
  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL https://get.docker.com/ | sh
    usermod -aG docker vagrant
    export OC_VERSION=v3.6.1
    wget https://github.com/openshift/origin/releases/download/$OC_VERSION/openshift-origin-client-tools-$OC_VERSION-008f2d5-linux-64bit.tar.gz
    tar xfz openshift-origin-client-tools-$OC_VERSION-008f2d5-linux-64bit.tar.gz
    mv openshift*/oc /usr/local/bin/

    #install Ansible
    apt-get -y update
    apt-get -y install software-properties-common
    apt-add-repository -y ppa:ansible/ansible
    apt-get -y update
    apt-get -y install ansible

    apt-get install -y python-pip git
    pip install docker-py    
    #install compose
    curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose    
  SHELL
end
