Vagrant.configure("2") do |config|
  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.hostname = "node1"
    node1.vm.network "forwarded_port", guest: 8080, host: 58080
    node1.vm.network "forwarded_port", guest: 8181, host: 58181
    node1.vm.network "forwarded_port", guest: 80, host: 580

    node1.vm.network "private_network", ip: "192.168.33.10"
    node1.vm.provision :shell, path: "bootstrap.sh"
    node1.vm.synced_folder "./data", "/vagrant_data"

    node1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]     
      vb.memory = "1024"
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.box = "centos/7"
    node2.vm.hostname = "node2"
    node2.vm.network "forwarded_port", guest: 8080, host: 48080
    node2.vm.network "forwarded_port", guest: 8181, host: 48181
    node2.vm.network "forwarded_port", guest: 80, host: 480

    node2.vm.network "private_network", ip: "192.168.33.11"
    node2.vm.provision :shell, path: "bootstrap.sh"
    node2.vm.synced_folder "./data", "/vagrant_data"

    node2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]     
      vb.memory = "1024"
    end
  end  
end
